[project]
name = "blossom"
version = "1.0"
description = "Primitive email app that supports receiving and sending emails built on Adw and Gtk"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "colorama>=0.4.6",
    "pycairo>=1.29.0",
    "pygobject>=3.56.2",
    "pygobject-stubs>=2.17.0",
    "pyperclip>=1.11.0",
    "secretstorage>=3.5.0",
    "appimage>=2.0.0",
]

[dependency-groups]
dev = [
    "pygobject-stubs>=2.17.0",
]

[project.scripts]
blossom = "blossom.main:main"

[project.gui-scripts]
blossom = "blossom.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.wheel]
packages = ["src/blossom"]

[tool.appimage.build]
app = "blossom"	
entry_point = "blossom.main:main"
python = "3.14"
icon = "src/blossom/assets/blossom.svg"
update_info = "gh-releases-zsync|yehorscode|blossom|latest|Blossom-*x84_64.AppImage.zsync"
